apiVersion: helm.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-chart
  namespace: gotk-apps
spec:
  interval: 5m
  chart:
    spec:
      chart: 'podinfo/podinfo'
      version: '5.0.3'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: gotk-apps
      interval: 1m
  values:
    replicaCount: 2
